__author__ = 'alexander'
import turtle

t = turtle.Turtle()
s = turtle.Screen()

#t.pendown()
#t.pencolor('red')
#t.forward(100)
def shape():
    turtle.shape("circle")
    turtle.shapesize(5,2)
    turtle.tilt(30)
    turtle.fd(50)
    turtle.tilt(30)
    turtle.fd(50)
    turtle.tilt(30)
    turtle.left(90)
    turtle.tilt(30)
    turtle.fd(50)
    turtle.tilt(30)
    turtle.fd(50)
    turtle.tilt(30)
    turtle.left(90)
    turtle.tilt(30)
    turtle.fd(50)
    turtle.tilt(30)
    turtle.fd(50)
    turtle.tilt(30)
    turtle.fd(50)
    turtle.tilt(30)
    turtle.fd(50)
    turtle.tilt(30)
    turtle.fd(50)
    turtle.left(90)
    turtle.tilt(30)
    turtle.fd(50)
    turtle.tilt(30)
    turtle.fd(50)
print(shape())

s.mainloop()
#help(turtle.Turtle)
